version: '3.7'
services:
  web:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/labelit
    ports:
      - '8001:8000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - db:/data/db
    ports:
      - '27017:27017'

volumes:
  db:
